### ISSUE TITLE
Request: .nsp format

### ISSUE THREAD

**Issue by MudkipBanana** [XorTroll/PlayerNX#3]
For cfw users, this would be a nice quality of life change.

**Comment by stipafk** [comment]
its not first problem for fix, i think needed defer. First problem video size and audio. i want fix it

**Comment by ThatNerdyPikachu** [comment]
What, NSPs aren't videos...

**Comment by WinterMute** [comment]
.nsp will get you banned please don't use or ask for them.

**Comment by XorTroll** [comment]
I may release a NSP version with the next update, as now we can make legal homebrew NSPs
